# Generated by Django 4.2.16 on 2024-11-08 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Single Flower', 'Single Flower'), ('Mixed Flower Arrangement', 'Mixed Flower Arrangement'), ('Flower Bouquet', 'Flower Bouquet'), ('Wedding Bouquet', 'Wedding Bouquet'), ('Seasonal Bouquet', 'Seasonal Bouquet'), ('Birthday Bouquet', 'Birthday Bouquet'), ('Anniversary Bouquet', 'Anniversary Bouquet'), ('Custom Design Bouquet', 'Custom Design Bouquet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
